In [1]:
import numpy as np
a = [1, 2, 3, 4, 5]
print(a)

[1, 2, 3, 4, 5]


In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a)
print(a[:6])
print(a[5])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
6


In [3]:
a_mul = np.array([[[1, 2, 3, 1],
                   [4, 5, 6, 1],
                   [7, 8, 9, 1],
                   [10, 11, 12, 1]],
                  [[1, 1, 1, 1],
                    [1, 1, 1, 1],
                    [1, 1, 1, 1],
                    [1, 1, 1, 1]]])

print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)


(2, 4, 4)
3
32
int64


In [4]:
a = np.array([[1, 2, 3],
              [4, "5", 6],
              [7, 8, 9]], dtype = np.float32)
print(a.dtype)
print(a[0][0].dtype)
print(a[1, 1])

float32
float32
5.0


When we have something that is not a primitive datatype that we can typecast into, everything become an object. This means dynamictyping. When we want all the number into same datatype as dictionary we have to use python style object.

In [5]:
d = {'1': 'A'}

a = np.array([[1, 2, 3],
              [4, d, 6],
              [7, 8, "hello"]])
print(a.dtype)
print(type(a[1][0]))

object
<class 'int'>


Filling Arrays using different functions.

In [6]:
a = np.full((2, 3, 4), 9)
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [12]:
a = np.zeros((5, 5, 2))
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [14]:
np.ones((5, 3, 3))
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


With np.arrange we can specify the beginning step, the end step and step size.

In [16]:
x_values = np.arange(0, 500, 5)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495]


With np.linspace we can specify the beginning step, the end step and the step count.

In [19]:
y_values = np.linspace(0, 100, 5)
print(y_values)

[  0.  25.  50.  75. 100.]


NaN and Inf

In [24]:
print(np.nan)
print(np.inf)

print(np.sqrt(-1))
print(np.array([10]) / 0)

nan
inf
nan
[inf]


/tmp/ipython-input-1099712202.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
/tmp/ipython-input-1099712202.py:5: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10]) / 0)


Mathematical Operations in Numpy

In [27]:
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 5, 10, 15, 15]

arrayOne = np.array(listOne)
arrayTwo = np.array(listTwo)

print(listOne * 2)
print(arrayTwo * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 4 10 20 30 30]


In [28]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1],
              [2]])
print(a1 + a2)

[[2 3 4]
 [3 4 5]]


In [30]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.sqrt(a))
print(np.sin(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [33]:
b = np.array([1, 2, 3])
b = np.append(a, [7, 8, 9])

b = np.insert(a, 3, [8, 9])
print(b)

[1 2 3 8 9 4 5 6]


In [36]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.delete(a, 1))
print(np.delete(a, 1, axis = 0)) #got rid of the second row
print(np.delete(a, 1, axis = 1)) #got rid of the second column



[1 3 4 5 6]
[[1 2 3]]
[[1 3]
 [4 6]]


Structuring the arrays

In [46]:
a = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
               [11, 12, 13, 14, 15],
               [16, 17, 18, 19, 20]])
print(a.shape)
print(a.reshape((5,4)))
print(a.reshape((20,)))
print(a.reshape((2, 10)))
print(a.reshape((2, 5, 2)))

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


In [51]:
a = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
               [11, 12, 13, 14, 15],
               [16, 17, 18, 19, 20]])
a.reshape((10, 2))
print(a)

a.resize((10, 2))
print(a)

print(a.flatten())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [56]:
a = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
               [11, 12, 13, 14, 15],
               [16, 17, 18, 19, 20]])

var1 = a.flatten()
var1[2] = 100
print(var1)
print(a)

var2 = a.ravel()
var2[2] = 100
print(var2)
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [55]:
var = [v for v in a.flat]
print(var)

[np.int64(1), np.int64(2), np.int64(100), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]
